#!/bin/sh

verbose()
{
    if [ -n "$GLOBAL_VERBOSE" ]; then
        echo "HOOK: 05-remount_rw: $@"
    fi
}

verbose "has started"

echo "REMOUNT_ROOTFS_RW_COMMAND=/etc/init.d/remount_rw" >> /etc/sysconfig/init

verbose "finished"
