#!/bin/bash

CONF=/etc/systemd/journald.conf

[ -f $CONF ] || exit 0

sed -i \
    -e s/"#Storage.*"/"Storage=volatile"/ \
    -e s/"#ForwardToConsole.*"/"ForwardToConsole=yes"/ \
    -e s/"#ForwardToKMsg.*"/"ForwardToKMsg=yes"/ \
    -e s%"#TTYPath=.*"%"TTYPath=/dev/tty12"% \
    -e s/"#MaxLevelConsole.*"/"MaxLevelConsole=info"/ \
    -e s/"#MaxLevelKMsg.*"/"MaxLevelKMsg=err"/ \
    -e s/"#RuntimeMaxUse.*"/"RuntimeMaxUse=5M"/ \
    -e s/"#SystemMaxUse.*"/"SystemMaxUse=50M"/ \
    /etc/systemd/journald.conf

    rm -Rf /var/log/journal/* 2>/dev/null || :