#!/bin/bash

VERSION=4.6

for FILE in x86_64-alt-linux-gcc x86_64-alt-linux-g++ x86_64-alt-linux-cpp x86_64-alt-linux-gcov x86_64-alt-linux-gfortran
do
    alternatives-manual /usr/bin/$FILE /usr/bin/$FILE-$VERSION
done

alternatives-update

echo "/opt/cuda/lib64" >/etc/ld.so.conf.d/cuda-toolkit.conf

cat <<E_O_F >/etc/bashrc.d/cuda-toolkit.sh
export PATH=$PATH:/opt/cuda/bin

E_O_F
chmod 755 /etc/bashrc.d/cuda-toolkit.sh

