#!/bin/sh
# see also m-p-d::profiles/live/image-scripts.d/init3-services

[ -x /sbin/chkconfig -o -x /bin/systemctl ] || exit 0

switch() {
	case "$2" in
	on)
		cc=on; sc=enable;;
	off)
		cc=off; sc=disable;;
	esac

	{
		[ ! -x /bin/systemctl ] ||
			/bin/systemctl --no-reload $sc $1.service

		[ ! -x /sbin/chkconfig ] ||
			/sbin/chkconfig $1 $cc
	} 2>/dev/null
}



ENABLE="
rpcbind
sshd
kheaders
xinetd
smartd
bluetoothd
x11presetdrv
NetworkManager
livecd-save-nfs
virtualbox
libvirtd
"

DISABLE="
bind
cups
livecd-online-repo
"


for i in $ENABLE;  do switch $i on;  done
for i in $DISABLE; do switch $i off; done
:
