#!/bin/sh

echo Changes for EVM edition

[ -f /etc/vmware/not_configured ] && rm -f /etc/vmware/not_configured

echo "ZONE=\"Europe/Minsk\"" >> /etc/sysconfig/clock
cp -f /usr/share/zoneinfo/Europe/Minsk /etc/localtime

# Do not need to shutdown network on network-based workstations or reboot/poweroff
# In other case shutdoun process will stuck here
# should not affect LiveCD
[ -f /lib/systemd/system/network.service ] && \
  sed -i -e s%"^ExecStop=.*"%"ExecStop=/bin/true"% /lib/systemd/system/network.service

echo Disabling ICMP redirects
cat <<E_O_F >>/etc/net/sysctl.conf
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
E_O_F

# For local MPI
mpi-selector --set openmpi --system --yes

cat <<E_O_F >/etc/bashrc.d/mpi.sh

for f in /etc/profile.d/mpi*.sh; do
    if [ -r "\$f" ]; then
	. "\$f"
    fi
done
unset f
E_O_F

chmod 755 /etc/bashrc.d/mpi.sh

XFCE4_CONF=".config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"

# use bash by default (avoid mike's lovely zsh :-E)
[ -z "$GLOBAL_USERS" ] ||
	echo "$GLOBAL_USERS" \
	| tr ' ' '\n' \
	| while IFS=':' read login passwd admin sudo; do
		chsh -s "/bin/bash" "$login" ||:
		# Set neutral picture for XFCE4 background.
		[ -f /home/devel/$XFCE4_CONF ] && \
		  sed -i -e s/"slinux_june_2017_1920x1080.jpg"/"vladstudio_aquarium2_1680x1050.jpg"/ /home/devel/$XFCE4_CONF ||:
	done

# Allow usage of libvirtd for anybody
cat <<E_O_F >/etc/polkit-1/rules.d/99-libvirt.rules
/* -*- mode: js; js-indent-level: 4; indent-tabs-mode: nil -*- */

// Enable usage of libvirt for everybody

polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.libvirt.unix.manage") == 0) {
        return polkit.Result.YES;
    }
});
E_O_F

# Allow nested virtualisation
cat <<E_O_F >/etc/modprobe.d/kvm_intel-nested.conf
options kvm_intel nested=1
E_O_F

# No nouveau please
cat <<E_O_F >/etc/modprobe.d/blacklist-nouveau.conf
blacklist nouveau
E_O_F

# Start XFCE4 by default
cat <<E_O_F >/etc/sysconfig/desktop
Xfce4
E_O_F

