#!/bin/sh

echo Changes for EVM edition

[ -f /etc/vmware/not_configured ] && rm -f /etc/vmware/not_configured

echo "ZONE=\"Europe/Minsk\"" >> /etc/sysconfig/clock
cp -f /usr/share/zoneinfo/Europe/Minsk /etc/localtime

echo "ALT Linux 7.0.5 BSUIR/EVM edition" > /etc/altlinux-release

echo Disabling ICMP redirects
cat <<E_O_F >>/etc/net/sysctl.conf
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
E_O_F


# For local MPI
mpi-selector --set openmpi --system --yes

cat <<E_O_F >/etc/bashrc.d/mpi.sh

for f in /etc/profile.d/mpi*.sh; do
    if [ -r "\$f" ]; then
	. "\$f"
    fi
done
unset f
E_O_F

chmod 755 /etc/bashrc.d/mpi.sh

# use bash by default
chsh -s "/bin/bash" "altlinux"

# add to groups
for group in vboxusers vmusers ; do
    usermod -a --groups "$group" "altlinux" ||:
done

