#!/bin/sh

echo Changes for EVM edition

[ -f /etc/vmware/not_configured ] && rm -f /etc/vmware/not_configured

echo "ZONE=\"Europe/Minsk\"" >> /etc/sysconfig/clock
cp -f /usr/share/zoneinfo/Europe/Minsk /etc/localtime


echo Disabling ICMP redirects
cat <<E_O_F >>/etc/net/sysctl.conf
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
E_O_F

# For local MPI
mpi-selector --set openmpi --system --yes

cat <<E_O_F >/etc/bashrc.d/mpi.sh

for f in /etc/profile.d/mpi*.sh; do
    if [ -r "\$f" ]; then
	. "\$f"
    fi
done
unset f
E_O_F

chmod 755 /etc/bashrc.d/mpi.sh

# use bash by default (avoid mike's lovely zsh :-E)
[ -z "$GLOBAL_USERS" ] ||
	echo "$GLOBAL_USERS" \
	| tr ' ' '\n' \
	| while IFS=':' read login passwd admin sudo; do
		chsh -s "/bin/bash" "$login" ||:
	done

# Allow usage of libvirtd for anybody
cat <<E_O_F >/etc/polkit-1/rules.d/99-libvirt.rules
/* -*- mode: js; js-indent-level: 4; indent-tabs-mode: nil -*- */

// Enable usage of libvirt for everybody

polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.libvirt.unix.manage") == 0) {
        return polkit.Result.YES;
    }
});
E_O_F

# Allow nested virtualisation
cat <<E_O_F >/etc/modprobe.d/kvm_intel-nested.conf
options kvm_intel nested=1
E_O_F
