#!/bin/sh

echo Changes for EVM edition

[ -f /etc/vmware/not_configured ] && rm -f /etc/vmware/not_configured
#depmod -a


ENABLE="
rpcbind
sshd
xinetd
smartd
NetworkManager
bluetoothd
"

DISABLE="
bind
cups
livecd-online-repo
"

for i in $ENABLE;  do chkconfig $i on  2>/dev/null; done
for i in $DISABLE; do chkconfig $i off 2>/dev/null; done

echo "ZONE=\"Europe/Minsk\"" >> /etc/sysconfig/clock
cp -f /usr/share/zoneinfo/Europe/Minsk /etc/localtime

#echo "BSUIR/EVM edition based on ALTLinux" > /etc/altlinux-release

echo Disabling ICMP redirects
cat <<E_O_F >>/etc/net/sysctl.conf
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
E_O_F

